package br.com.softbox.ejb.entity;
// Generated 17/08/2015 18:01:24 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Questionnaire generated by hbm2java
 */
@Entity
@Table(name = "questionnaire", catalog = "questionnaire")
public class Questionnaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5108333513654882826L;
	private long id;
	private Administrator administrator;
	private boolean published;
	private String name;
	private Date creationDate;
	private List<Question> questions = new ArrayList<Question>(0);
	private Set<Answer> answers = new HashSet<Answer>(0);

	public Questionnaire() {
	}

	public Questionnaire(long id, Administrator administrator) {
		this.id = id;
		this.administrator = administrator;
	}

	public Questionnaire(long id, Administrator administrator, boolean published, String name, Date creationDate, List<Question> questions,
			Set<Answer> answers) {
		this.id = id;
		this.administrator = administrator;
		this.published = published;
		this.name = name;
		this.creationDate = creationDate;
		this.questions = questions;
		this.answers = answers;
	}

	public Questionnaire(long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "administrator_id", nullable = false)
	public Administrator getAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(Administrator administrator) {
		this.administrator = administrator;
	}

	@Column(name = "published")
	public boolean getPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionnaire", orphanRemoval = true)
	@OrderBy("creationDate")
	public List<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionnaire")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

	@Override
	public String toString() {
		return "Questionnaire [id=" + id + "]";
	}

}
